name: Update Version and Build Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step to upgrade version from SNAPSHOT to a full version (if needed)
    - name: Replace SNAPSHOT with version number
      run: |
        sed -i 's/-SNAPSHOT//g' pom.xml

    # Step to bump the version using the bump action
    - name: Bump version
      id: bump
      uses: mickem/gh-action-bump-maven-version@v1.0.0

    # Save the new version as an environment variable to use in the next steps
    - name: Set NEW_VERSION
      run: echo "NEW_VERSION=${{ steps.bump.outputs.new_version }}" >> $GITHUB_ENV

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t stavtsdaka/githubactions:$NEW_VERSION .

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: |
        docker push stavtsdaka/githubactions:$NEW_VERSION
